# Generated by Django 4.2.7 on 2024-09-09 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Phone Number')),
                ('subject', models.CharField(default='General Inquiry', max_length=100, verbose_name='Subject')),
                ('form_of_contact', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Phone')], default='email', max_length=10, verbose_name='Preferred Contact Method')),
                ('question_category', models.CharField(choices=[('general_enquiry', 'General Enquiry'), ('placed_order', 'Placed Order'), ('delivery', 'Delivery'), ('custom_bake_request', 'Custom Bake Request'), ('special_events', 'Special Events'), ('other', 'Other')], default='general_enquiry', max_length=50, verbose_name='Enquiry Type')),
                ('message', models.TextField(max_length=3000, verbose_name='Message Details')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20, verbose_name='Enquiry Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted On')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
